### ISSUE TITLE
Look at Transcript Workflow 

### ISSUE THREAD

**Issue by caseyburden** [NYCDA-Processing/RecruiterSDK#1]
backwards compatibility not working.

**Comment by caseyburden** [comment]
@ncooke or @JadeKilburn  can we get a break down of what is going wrong with the workflow?

**Comment by ncooke** [comment]
Will do.  Our strategy is to review every W/F related to receiving HS and College transcripts (official and unofficial).

**Comment by caseyburden** [comment]
but what is the issue?  what is the bug that is occurring that needs to be fixed?

we can delete this issue and start one that is more descriptive.

**Comment by caseyburden** [comment]
Part of the problem was an activity code got changed a while back and no one noticed.

I did the following:
- correct the wrong activity code
- adjusted two default workflows to work with our codes
- deactivated our other "receive item" workflows

Now the only way to collect a transcript is to enter in College or High School History
