### ISSUE TITLE
edit workflow that receives Unofficial College Transcript

### ISSUE THREAD

**Issue by ncooke** [NYCDA-Processing/RecruiterSDK#11]
low priority--

It was requested that the we edit the item received entry for unofficial college transcripts received (see Closed Activities for Louise Pierosan for example).  Currently, it shows as "College Transcript (In Progress)."  

To clarify it could read "College Transcript Received (Unofficial)."

**Comment by caseyburden** [comment]
This change was made a before.  Should be correct.
