### ISSUE TITLE
edit workflow for receiving transcripts

### ISSUE THREAD

**Issue by ncooke** [NYCDA-Processing/RecruiterSDK#12]
Currently, in the closed activities transcripts marked received show "Recruiter Admin" in the field "Created By."  Could we edit the workflow to indicate - in the field - the name of the user that updated the academic record, which generated the workflow?

**Comment by caseyburden** [comment]
We can't change the "Created by" field and actually should never try.  That field is great to help debug a problem.  I did, however, add a new field "received by"  which gets populated by the workflow with the person who created the item received.  I believe that should work, but if it doesn't let me know and we can try something different.  I also added "received by" to the views.
