### ISSUE TITLE
Recuiters are still using the W/F's and Dialogs instead of creating tasks

### ISSUE THREAD

**Issue by JadeKilburn** [NYCDA-Processing/RecruiterSDK#23]
This causes problems when something goes wrong.
If we do it we can fix it easily but if they run it, its harder to track what went wrong and when. 
Can we remove their access to these w/f's and dialogs - reject, withdraw and move/defer

**Comment by caseyburden** [comment]
Unfortunately, I don't seem to have any way of editing or creating the views for Workflows.  They are locked in the system.  My best advice right now is to come up with a naming convention that clearly marks Processing Workflows vs. Admissions or General.  That and also reinforcing to the recruiters that the process has changed.
