### ISSUE TITLE
{N40 - Update Confirmed Status}

### ISSUE THREAD

**Issue by JadeKilburn** [NYCDA-Processing/RecruiterSDK#27]
This sets off when deposit processed date and the enrolment agreement received date is entered.

It is cancelling when the prospect is already confirmed therefore does not run the auto enroll to take them from Confirmed to enrolled. 

We need it to let confirmed statuses go through this process

**Comment by ncooke** [comment]
@caseyburden - please assign this workflow to me to make edits.

**Comment by caseyburden** [comment]
done.  It will need to be re activated.

**Comment by ncooke** [comment]
the w/f was edited and reactivated.  Thanks!
