### ISSUE TITLE
Track multiple actions on one task

### ISSUE THREAD

**Issue by ncooke** [NYCDA-Processing/RecruiterSDK#3]
Need the task to allow for follow up with several departments.

**Comment by ncooke** [comment]
Each department is to have a check box to mark if follow up is needed.

List:
Bursar
Coordinator
Dir of Edu
Financial Aid
Registrar
Other

**Comment by caseyburden** [comment]
Create a view on a task that is For Processing Use Only

I'll show you. Issue #2

**Comment by caseyburden** [comment]
We may want to explore if there may be another way to accomplish this, but I like the initiative. :+1:

**Comment by ncooke** [comment]
Admin Form was created (a version of the Task Form) for Processing Use Only and allows for tracking several tasks on one form.

-The form has a check box for each department that Processing needs to follow up with and a notes field next to it.

-The follow up is to be completed _after_ an admitted student's folder is sent to the Registrar but _prior to_ completing the requirements for enrollment.
