### ISSUE TITLE
Event Metrics Not Calculating

### ISSUE THREAD

**Issue by ncooke** [NYCDA-Processing/RecruiterSDK#41]
How are Skype events metrics calculated vs. events, such as Miami auditions, where there are no event metrics other than number of participants?

![skypemetrics](https://cloud.githubusercontent.com/assets/8712870/5532936/9114aace-8a0c-11e4-88d6-69c42b6ba248.png)
![miaminometrics](https://cloud.githubusercontent.com/assets/8712870/5532969/1e8c31f6-8a0d-11e4-97b5-15e181d5ec4f.png)

**Comment by caseyburden** [comment]
answered with #43
