### ISSUE TITLE
{Event Metrics} Currently needs to be manually run

### ISSUE THREAD

**Issue by ncooke** [NYCDA-Processing/RecruiterSDK#43]
###### Background

DOA Views event metrics daily to track audition attendance and the breakdown by prospect status.
###### Issue At First Glance

The Workflow Scheduler is set to run the Event Metrics w/f at 5am daily, but it has not run in over a month. It appears to be hung up waiting for a step in the process to complete.

**Comment by caseyburden** [comment]
We had Ellucian look at our Workflow Scheduler today.  So it "SHOULD" run now.

Please let me know if it stops again.
